### ISSUE TITLE
createBlockBlobFromStream result object may differ when uploading blobs below or above 32MB

### ISSUE THREAD

**Issue by sitanshu-zymr** [Azure/azure-storage-node#417] opened 2018-02-24 06:36 UTC
When i uploading any file >40 MB it returns me:

**result**: 
`{
  "commmittedBlocks": [
    "d603d17e-000000",
    "d603d17e-000001",
    "d603d17e-000002",
    "d603d17e-000003",
    "d603d17e-000004",
    "d603d17e-000005",
    "d603d17e-000006",
    "d603d17e-000007",
    "d603d17e-000008",
    "d603d17e-000009",
    "d603d17e-000010",
    "d603d17e-000011",
    "d603d17e-000012",
    "d603d17e-000013",
    "d603d17e-000014",
    "d603d17e-000015",
    "d603d17e-000016",
    "d603d17e-000017",
    "d603d17e-000018"
  ]
}`
**response**: 
`{"isSuccessful":true,"statusCode":201,"body":"","headers":{"transfer-encoding":"chunked","content-md5":"0GODTWwxGhgPloFfcQ/N/A==","last-modified":"Fri, 23 Feb 2018 12:47:04 GMT","etag":"\"0x8D57ABB8A94FCB8\"","server":"Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0","x-ms-request-id":"a4a8f7af-001e-012f-77a4-ac6642000000","x-ms-version":"2016-05-31","x-ms-request-server-encrypted":"true","date":"Fri, 23 Feb 2018 12:47:03 GMT","connection":"close"}}
`
In the result object, there is no proper data what I expect after upload…

While upload any <40 MB file I am getting proper data in result object:
i.e.
{
  "container": "xxx-store",
  "name": "_xxx_1b7fa420-188f-11e8-bb92-4b0f04f4bcc1.png",
  "lastModified": "Fri, 23 Feb 2018 11:46:03 GMT",
  "etag": "\"0x8D57AB30432ED62\"",
  "requestId": "68b4c3b6-701e-007d-6f9b-ac3de5000000",
  "contentSettings": {
    "contentMD5": "vCB6GSdHp8li1fErxAkdLg=="
  }
}
Which is right as per document. I want it to fix ASAP. Can you please take a look?

Also, I have tested in createBlockBlobFromLocalFile same result: >40 there is no proper result:

While uploading any file I should get proper result:
```
{
  "container": "xxx-store",
  "name": "_xxx_1b7fa420-188f-11e8-bb92-4b0f04f4bcc1.png",
  "lastModified": "Fri, 23 Feb 2018 11:46:03 GMT",
  "etag": "\"0x8D57AB30432ED62\"",
  "requestId": "68b4c3b6-701e-007d-6f9b-ac3de5000000",
  "contentSettings": {
    "contentMD5": "vCB6GSdHp8li1fErxAkdLg=="
  }
}

``` 

Size should not be a cause.

**Comment by sitanshu-zymr** [comment] 2018-02-27 07:34
take a look:

```
function uploadBlob(key, stream, cb) {
  BLOBService.createBlockBlobFromStream(“xxxx”, key, stream, stream.size, function (error, result, response) {
    if(error){
      logger.error(error);
    cb(error);
    } else {
      logger.info(result, response);
        var file = {
            etag: result.etag,
            length: stream.size,
            name: result.name,
            container: result.container,
            digest: 'md5-' + result.contentSettings.contentMD5
        };
        cb(null, file);
    }
  });
}
```
When file is >40 MB at that time I didn't get proper result Object. 

I am sharing files with you.

>40 MB: https://drive.google.com/file/d/1oZmifAe8wg6zslo0j0z_cimD9B3t5Q-N/view?usp=sharing
MD5: 2adaec6d5c4cd4ad2dd99371bcb329cd

<40 MB: https://drive.google.com/file/d/1-Ec3ub8q4aBDDP_k5xyDEiUPMwIy97Af/view?usp=sharing
MD5: 134d593f31ad60e1f1f9494fd96f6f09

**Comment by XiaoningLiu** [comment] 2018-03-02 05:10
hi @sitanshu-zymr It's by design.

When file size smaller than a default threshold size, we will upload the file with ONE HTTP PUT REQUEST.

When the file size larger than that, we will split the whole file into blocks, and upload blocks one by one with MANY HTTP requests, and finally a PUT BLOCK LIST HHTP request will be made to commit all the blocks. In this case, the returned data is not what you thought.

What I recommend is, you can call blobService.getBlobProperties() in the uploading callback method to get properties of the blob you uploaded.

**Comment by sitanshu-zymr** [comment] 2018-03-06 06:31
Hi @XiaoningLiu Thanks for a reply with a suggestion.

But if i call blobService.getBlobProperties() in the uploading callback method to get properties, in this case, i have to call 1 more API request.

**Comment by XiaoningLiu** [comment] 2018-03-06 07:00
@sitanshu-zymr I'm afraid so. For Azure Storage REST API [PUT BLOCK LIST](https://docs.microsoft.com/en-us/rest/api/storageservices/put-block-list), the response doesn't contain information you required.


ETag | The entity tag contains a value that the client can use to perform conditional GET/PUT operations by using the If-Matchrequest header. If the request version is 2011-08-18 or newer, the ETag value will be in quotes.
-- | --
Last-Modified | The date/time that the blob was last modified. The date format follows RFC 1123. For more information, see Representation of Date-Time Values in Headers.Any operation that modifies the blob, including an update of the blob's metadata or properties, changes the last modified time of the blob.
Content-MD5 | This header is returned so that the client can check for message content integrity. This header refers to the content of the request, meaning, in this case, the list of blocks, and not the content of the blob itself.
x-ms-request-id | This header uniquely identifies the request that was made and can be used for troubleshooting the request. For more information, see Troubleshooting API Operations.
x-ms-version | Indicates the version of the Blob service used to execute the request. This header is returned for requests made against version 2009-09-19 and later.
Date | A UTC date/time value generated by the service that indicates the time at which the response was initiated.
x-ms-request-server-encrypted: true/false | Version 2015-12-11 or newer. The value of this header is set to true if the contents of the request are successfully encrypted using the specified algorithm, and false otherwise.

**Comment by XiaoningLiu** [comment] 2018-03-06 08:35
I got your point. It makes sense to ask for a persistence result. But the API response will not change until a major version release.

By all means, blobService.getBlobProperties() call is required to retrieve latest properties for a blob uploaded by multi HTTP requests.

**Comment by sitanshu-zymr** [comment] 2018-03-06 09:23
Ok @XiaoningLiu Thanks for the discussion. Hoping that it will reflect in the next release.

**Comment by vitoravale** [comment] 2018-03-20 14:35
@sitanshu-zymr this solved for me:

```javascript
if (!result.commmittedBlocks)
    return callback(error, result)
blobService.getBlobProperties(config.containerName, blobName, options, (er, re) => callback(er, re))
```

**Comment by arryon** [comment] 2018-05-11 12:48
@XiaoningLiu I wanted to point out that this behaviour is very weird. It seems to me that information is just being thrown away. If you look at blobservice.core.js, the code that commits the blocks to a blob after block upload is

```
self.commitBlocks(container, blob, blockList, options, function (error, blockList, response) {
        self.logger.debug(util.format('Blob %s committed', blob));

        if (error) {
          chunkStream.finish();

          callback(error);
        } else {
          blobResult['commmittedBlocks'] = blockIds;

          chunkStream.finish();
          callback(error, blobResult, response);
        }
      });
```
In fact the information being returned from the Azure server, in the variable 'blockList' is at this point exactly the same as it would be in the regular <32MB PUT scenario. But instead of returning this data, only 'committedBlocks' is inserted into blobResult and returned.

I would vote for a PR in which the information from blockList in L#5093 is also copied to the blobResult, saving one API call.

**Comment by XiaoningLiu** [comment] 2018-05-14 08:00
@arryon What does L#5093 provide are container and blob names right? Any other information do you want to provide into BlobResult?

The default 32MB thereshold can be customized. The max size is limited by Azure server, should be 256MB. But if you set it a value smaller than 4MB. Then all the requests will perform 2-step upload - "upload block" and "commit blocks".

```
blobService.singleBlobPutThresholdInBytes = someValueInBytes;
```

**Comment by arryon** [comment] 2018-05-14 09:10
@XiaoningLiu Let me try and clarify the issue:

Say my streamLength is smaller than `singleBlobPutThresholdInBytes`. The request to create a Block Blob from stream gets sent to the function [_putBlockBlob](https://github.com/Azure/azure-storage-node/blob/master/lib/services/blob/blobservice.core.js#L4507). The result of this operation is a BlobResult with, among others, the parameters `container`, `etag`, `requestId`, `name`.

Say my streamLength is greather, the request is redirected to [_uploadContentFromChunkStream](https://github.com/Azure/azure-storage-node/blob/master/lib/services/blob/blobservice.core.js#L4856). As you know, this function uploads the stream into Blocks first, then commits a Blob based on the list of Blocks.
But: the result of the function [_commitBlocks as called here](https://github.com/Azure/azure-storage-node/blob/master/lib/services/blob/blobservice.core.js#L5093) is also a BlobResult, just like in _putBlockBlob, even though the variable is called `blockList`.

What I don't understand, is why in the latter case the BlobResult information is not passed into the final callback. This would, in some cases, save an extra API call.

**Comment by XiaoningLiu** [comment] 2018-05-15 08:27
@arryon Thanks for clarifying. I admit that it's inconvenience to have different behaviors for a single method. It's a history method design.

For the 2nd situation you described. Following screenshot describes what the `BlobResult` contains. 

I'm agree that passing the `BlobResult` to final will reduce an extra API call if we want to get the `etag` and `lastModified` of the blob just created, or `requestId` for the final commit block list request.

However, we should pay attention that the `contentMD5` returned for the 2nd situation is not the MD5 of the blob created. See https://docs.microsoft.com/en-us/rest/api/storageservices/put-block-list.  **It's confusing if we include it and pass to the final.**

Content-MD5 | This header is returned so that the client can check for message content integrity. This header refers to the content of the request, meaning, in this case, the list of blocks, and not the content of the blob itself.
-- | --

![image](https://user-images.githubusercontent.com/6889160/40044539-375b2cc2-585a-11e8-80a3-9f571b7890d8.png)

**Closed** 2019-05-06 01:53 UTC
Labels: feature request
