### ISSUE TITLE
Argument of type 'null' is not assignable to parameter of type 'TableContinuationToken'

### ISSUE THREAD

**Issue by samiyaakhtar** [Azure/azure-storage-node#596] opened 2019-07-15 16:55 UTC
### Which service(blob, file, queue, table) does this issue concern?
table

### Which version of the SDK was used?
2.10.3

### What's the Node.js/Browser version?
Node 12.4.0 npm 6.10.1

### What problem was encountered?
According to the docs, when querying a table using queryEntities, the continuationToken can be passed in as null or undefined (`Please use 'null' or 'undefined' if this is the first operation.`)
However, that does not compile: `Argument of type 'null' is not assignable to parameter of type 'TableContinuationToken'.`

### Have you found a mitigation/solution?
No

**Comment by Dustify** [comment] 2019-07-15 21:50
Duplicate of https://github.com/Azure/azure-storage-node/issues/545 (more information / workaround available)

**Comment by XiaoningLiu** [comment] 2019-07-17 02:32
@samiyaakhtar It's an know issue. Before we have a fix, please using workaround mentioned in another issue.

**Comment by samiyaakhtar** [comment] 2019-07-17 02:50
Will do, thanks @XiaoningLiu @Dustify

**Closed** 2021-09-28 02:45 UTC
Labels: bug
