### ISSUE TITLE
PutBlock occasionally fails with statusCode: 400 with Azure Storage JavaScript Client Library for Browsers

### ISSUE THREAD

**Issue by thiruma0203** [Azure/azure-storage-node#409] opened 2018-02-08 11:55 UTC
When Azure Storage JavaScript Client Library for Browsers is accessed with Mac Safari (10.1), uploading file intermittently fails.

Steps:
1. Download the latest package of Azure Storage JavaScript Client Library for Browsers, and simply host sample pages on any Web server.

2. Browse sample-blob.html with Mac Safari, then upload any file with size around 1GB to Azure Blob Storage with UploadBlob button.

3. Sometimes uploading  fails with error like below. Strangely Content-Length value is reported as zero. As far as I've tested, issue does not observed with Chrome.

[Log] StorageError (sample-blob.html, line 487)
code: "InvalidHeaderValue"
headername: "Content-Length"
headervalue: "0"
message: "The value for one of the HTTP headers is not in the correct format.↵RequestId:ba3c3037-001e-006d-76cf-a0ccab00000…"
name: "StorageError"
requestId: "ba3c3037-001e-006d-76cf-a0ccab000000"
statusCode: 400

[Error] Failed to load resource: the server responded with a status of 400 (HTTP/2.0 400) (data_1G, line 0)
[Error] TypeError: null is not an object (evaluating 'speedSummary.getAutoIncrementFunction')
（anonymous function） (azure-storage.blob.js:7112)
emit (azure-storage.common.js:37820)
_emitBufferData (azure-storage.common.js:1251)
_buildChunk (azure-storage.common.js:1217)
（anonymous function）
emit (azure-storage.common.js:37817)
readableAddChunk (azure-storage.common.js:36049)
onloadend (azure-storage.common.js:363)

**Comment by XiaoningLiu** [comment] 2018-03-02 05:03
Sorry for the late response, seems the data chunk reading has encountered into some issues on the Safari. There used to a similar issue on old Chrome versions about the Browser Blobs, which the Chrome has issues to release buffered Browser Blobs, resulting uploading failed after the buffer is full.

I'm not sure it's the same issue on Safari. Do you have latest Safari version installed? Can you have a try? Or can you try to upload smaller size files to see if there any regular failure patterns? I don't have a Safari (10.1) environment currently, will try to find some.

**Comment by XiaoningLiu** [comment] 2018-03-06 07:41
@thiruma0203 There is a similar issue https://github.com/Azure/azure-storage-node/issues/387 The issue is due to a network uploading failure.

In that thread, I uploaded a fixing version, and needs to enable retry policy. Please have a try and see if that works.

**Comment by thiruma0203** [comment] 2018-03-09 12:36
@XiaoningLiu 
Thanks for your comment. I could not test with newer version of Safari yet, however it does not reproduce with azurestoragejs-0.2.7-preview.14 so far. Will test suggested version as well.

**Comment by XiaoningLiu** [comment] 2018-03-12 03:47
From 0.2.7-preview.14, it applies a workaround for a GC bug of some browsers. If it works, most likely it's the the issue I mentioned in #387. 

We'll close the issue after some days, feel free to comments if the issue happens in the future.

**Closed** 2018-03-16 03:22 UTC
Labels: question
