### ISSUE TITLE
IE 11 crashes when large PDF files [around 400mb] are uploaded

### ISSUE THREAD

**Issue by SriChindain** [Azure/azure-storage-node#486] opened 2018-07-23 15:41 UTC
Hi,

While i try to upload large PDF files - greater than 400mb with IE11 browser using the below link, the browser crashes. I have attached the screen shot for your reference.

Link where i am trying to upload:
https://dmrelease.blob.core.windows.net/azurestoragejssample/samples/sample-blob.html

![image](https://user-images.githubusercontent.com/37663732/43087071-905238b4-8ebc-11e8-9a0b-95cfd2852589.png)

Thanks,

**Comment by XiaoningLiu** [comment] 2018-07-24 03:37
@SriChindain What's your IE11 version? Some old version IE11 has memory leaking bug.

See https://github.com/Azure/azure-storage-node/issues/325

**Comment by SriChindain** [comment] 2018-07-24 05:55
![image](https://user-images.githubusercontent.com/37663732/43119435-04d84dd2-8f34-11e8-8ce1-7ef6de005e21.png)

Is there any workaround for it?

**Comment by XiaoningLiu** [comment] 2018-07-26 09:53
@SriChindain Seems not an old version IE11. What's your IE11 latest update time? Can you provide steps to reproduce this issue? I'll try to reproduce your issue first on https://dmrelease.blob.core.windows.net/azurestoragejssample/samples/sample-blob.html

**Comment by SriChindain** [comment] 2018-07-26 11:21
Hi,

You can reproduce on
https://dmrelease.blob.core.windows.net/azurestoragejssample/samples/sample-blob.html.
Try to upload any pdf file over 400mb.

Thanks,

**Comment by XiaoningLiu** [comment] 2018-07-27 02:48
I cannot reproduce this issue.

Here is the 400MB pdf file I tried to upload: https://uofi.app.box.com/v/KaskaskiaMss-Searchable

My IE11 version and uploaded PDF file:

![image](https://user-images.githubusercontent.com/6889160/43298859-7afda0cc-918a-11e8-9f0f-b223e6d785e4.png)

Can you update your IE11 to latest and try again?

**Comment by XiaoningLiu** [comment] 2018-08-28 02:54
Hi, we will close this issue as we cannot reproduce and no more responses. Feel free reach to us if you need further support.

**Closed** 2019-05-06 02:23 UTC
Labels: question
