### ISSUE TITLE
File upload does not work in firfox

### ISSUE THREAD

**Issue by SriChindain** [Azure/azure-storage-node#430] opened 2018-03-22 14:22 UTC
The upload functionality mentioned in the link - [https://dmrelease.blob.core.windows.net/azurestoragejssample/samples/sample-blob.html] does not work in Firefox. I think file slice should be handled by mozSlice instead of slice to support Firfox browser as mention in the article - [https://developer.mozilla.org/en-US/docs/Web/API/Blob]

"Error: XHR error"

**Comment by XiaoningLiu** [comment] 2018-03-23 05:38
Hi @SriChindain 

Thanks for reporting it. What's your firefox version? Does the error pop up at the beginning of the upload?

It should work well on latest Firefox versions.

![image](https://user-images.githubusercontent.com/6889160/37813283-64789bc0-2e9f-11e8-9c2f-ee2e46147daf.png)

Best,
Xiaoning

**Comment by XiaoningLiu** [comment] 2018-03-23 05:41
Oh, I found that ***The support for blob.mozSlice() has been dropped with Firefox 30.*** in https://developer.mozilla.org/en-US/docs/Web/API/Blob. 

Seems Firefox 30 is pretty old.

**Comment by SriChindain** [comment] 2018-03-23 05:50
The version of the Firefox I am using in 59.0.1 (64-bit). I get this error when I start the upload.

I have observed this error in several other machines too!

**Comment by XiaoningLiu** [comment] 2018-03-23 05:57
I cannot re-produce the error when I updated my Firefox to 59.0.1. Can you give me more details? Like
* Does only Firefox have this error? How about Chrome.
* Error messages displayed in your browser Console (contains the callstack of the error)
* Network requests displayed in your browser console network tab
* What's the size of your file? Do it pop up this error immediately after clicking 'upload' or need some time before the error?

**Comment by SriChindain** [comment] 2018-03-23 06:13
Scenario: I opened the link - https://dmrelease.blob.core.windows.net/azurestoragejssample/samples/sample-blob.html, added storage account name and SAS and tried to retrieve containers.

Here is the stack trace of the error in console:
Error
​
columnNumber: 23
​
fileName: "https://dmrelease.blob.core.windows.net/azurestoragejssample/bundle/azure-storage.blob.js"
​
lineNumber: 44242
​
message: "XHR error"
​
stack: "[213]</</ClientRequest.prototype._onFinish/xhr.onerror@https://dmrelease.blob.core.windows.net/azurestoragejssample/bundle/azure-storage.blob.js:44242:23\n"
​
__proto__: Object { … }

**Comment by XiaoningLiu** [comment] 2018-03-23 12:30
@SriChindain Seems the error pops up at ```xhr.onerror``` event which is a ```XMLHTTPRequest``` object error. It usually happens due to network failure or input data invalid. To see if it's due to a network failure, you can open the network tab after the error happens and find out network requested marked as error. A paste of screenshot here is much appreciated:

At the same time, I'm still trying to re-produce the error on Firefox 59.0.1, but still can not reproduce. I tried on Windows 10 and MacOS with Firefox 59.0.1 64bit version. Do you use a Windows platform?

**Comment by vinjiang** [comment] 2018-04-20 05:01
Feel free to let us know if we can be of further assistance.

**Closed by vinjiang** 2018-04-20 05:01 UTC
Labels: help wanted
